name: Doxygen Documentation Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set Git Config
      - name: Set Git Configuration
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      # Create gh-pages Branch (if not exists)
      - name: Ensure gh-pages Branch
        run: |
          if [ "$(git branch --list gh-pages)" == "" ]; then
            git checkout --orphan gh-pages
          else
            git checkout gh-pages
          fi
          git reset --hard

        # Step 6: Commit and Force Push to gh-pages
      - name: Commit and Push to gh-pages
        run: |
          git add .
          git commit -m "Update Doxygen documentation"
          git push --force origin gh-pages

      #  Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/
