name: Doxygen Documentation Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Step : Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step: Create gh-pages Branch (if not exists)
      - name: Ensure gh-pages Branch
        run: |
          if [ "$(git branch --list gh-pages)" == "" ]; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
          fi

      # Step : Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html/
